spring: #develop DB??
  config:
    activate:
      on-profile: "devdb"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: star0
    url: jdbc:mysql://starsufersdev0.cvqoc00u0eis.ap-northeast-2.rds.amazonaws.com:3306/starsufersdev0?serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    password: 'star0000!'
  jpa:
    show-sql: 'false'
    generate-ddl: 'true'
    hibernate:
      ddl-auto: update
